name: lean's openwrt

# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#
# 警告:
# 对着屏幕的哥们, 我们允许你使用此脚本, 但不允许你抹去作者的信息, 请保留这段话.
# 你可以随意使用本脚本的代码, 但请注明出处.
#

on:
  push:
    branches:
      - lean
    paths:
      - '.github/workflows/main.yml'
      - 'patches/**'
      - 'config_rk3328'
      - 'nanopi-r2_linux_defconfig'
      - 'CHANGELOG.md'
  schedule:
    - cron: '00 18 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: lean

      # refer to klever1988/nanopi-openwrt and soffchen/NanoPi-R2S
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          git config --global user.name "Chuck"
          git config --global user.email "fanck0605@qq.com"

      - name: Install Repo
        run: |
          rm -rf repo
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          rm -rf repo

      - name: Initialization Source
        run: |
          rm -rf rk3328 && mkdir rk3328 && cd rk3328
          repo init -u https://github.com/fanck0605/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8

      # refer to coolsnowwolf/lede
      - name: Unlock some OpenWrt feeds
        run: |
          cd rk3328/friendlywrt
          sed -i 's/#src-git/src-git/g' ./feeds.conf.default

      # default version contains some bug
      - name: Upgrade Argon Theme
        run: |
          cd rk3328/friendlywrt/package/lean
          rm -rf luci-theme-argon
          git clone --single-branch -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git

      - name: Install filebrowser
        run: |
          rm -rf openwrt
          git clone --single-branch -b openwrt-18.06 https://github.com/project-openwrt/openwrt.git --depth=1
          mkdir -p rk3328/friendlywrt/package/ctcgfw
          cp -a openwrt/package/ctcgfw/filebrowser rk3328/friendlywrt/package/ctcgfw/
          cp -a openwrt/package/ctcgfw/luci-app-filebrowser rk3328/friendlywrt/package/ctcgfw/
          rm -rf openwrt

      # refer to klever1988/nanopi-openwrt, modified by Chuck <fanck0605@qq.com>
      - name: Install Openwrt patches
        run: |
          rm -rf openwrt
          git clone --single-branch https://github.com/openwrt/openwrt.git --depth=1
          cd openwrt
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/generic/backport-5.4
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/generic/pending-5.4
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/generic/hack-5.4
          ./scripts/patch-kernel.sh ../rk3328/kernel ./target/linux/octeontx/patches-5.4
          cp -a ./target/linux/generic/files/* ../rk3328/kernel/
          cd ../ && rm -rf openwrt

      # refer to klever1988/nanopi-openwrt, modified by Chuck <fanck0605@qq.com>
      - name: Enable Kernel futures
        run: |
          cd rk3328/kernel/
          wget -O net/netfilter/xt_FULLCONENAT.c https://raw.githubusercontent.com/Chion82/netfilter-full-cone-nat/master/xt_FULLCONENAT.c
          git apply ../../patches/001-kernel-add-full_cone_nat.patch
          cat ../../nanopi-r2_linux_defconfig > ./arch/arm64/configs/nanopi-r2_linux_defconfig

      - name: Customize Configuration Files
        run: |
          cat config_rk3328 > rk3328/configs/config_rk3328

      # 如果不喜欢互换, 直接注释即可
      - name: Swap wan and lan
        run: |
          cd rk3328/friendlywrt
          git apply ../../patches/003-openwrt-swap-wan-and-lan.patch

      # 编译时不要去除 set -e, 编译都报错了, 你还让它继续, 最后的固件能没有 bug?
      - name: Build FriendlyWrt
        run: |
          cd rk3328
          ./build.sh nanopi_r2s.mk

      - name: Fix FriendlyWrt rootfs owner and group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -o 100663296 $lodev rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount $lodev /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d $lodev

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          gzip rk3328/out/*.img
          cp rk3328/out/*.img* ./artifact/

      # 保存交叉编译配置, 需要先设置平台
      - name: Save Configurations
        run: |
          cd rk3328/friendlywrt
          ./scripts/diffconfig.sh > ../../artifact/config-lite
          cp .config ../../artifact/config-full
          cd ../kernel
          export PATH=/opt/FriendlyARM/toolchain/6.4-aarch64/bin/:$PATH
          export CROSS_COMPILE='aarch64-linux-gnu-'
          export ARCH=arm64
          make savedefconfig
          cp .config ../../artifact/kconfig-full
          cp defconfig ../../artifact/kconfig-lite

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt
          path: ./artifact/
